### ISSUE TITLE
1062, "Duplicate entry '16688' for key 'user_id'"

### ISSUE THREAD

**Issue by antoinelb** [SALTISES4/dalite-ng#105]
https://sentry.io/share/issue/e9d4d0f5d4ad426d8bda47341b2a9584/

**Comment by antoinelb** [comment]
https://sentry.io/share/issue/e9d4d0f5d4ad426d8bda47341b2a9584/

**Comment by sameerbhatnagar** [comment]
This was a mixup. It is resolved
